name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t <username>/<appname> .
      - name: Publish image to docker hub
        run: docker push <username>/<appname>:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Pull image from docker hub
        run: docker pull <username>/<appname>:latest

      - name: Delete Old Container
        run: docker-compose down

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env  # For verification

      - name: Start Containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Remove old images
        run: docker image prune -a -f
